# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"<\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"%\n\rServerRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"0\n\x0eServerResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"8\n\x0fRegisterRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x45\n\x0b\x43hatService\x12\x36\n\nChatStream\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x01\x30\x01\x32\x80\x01\n\x0bNameService\x12\x36\n\tGetServer\x12\x13.chat.ServerRequest\x1a\x14.chat.ServerResponse\x12\x39\n\x08Register\x12\x15.chat.RegisterRequest\x1a\x16.chat.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=80
  _globals['_SERVERREQUEST']._serialized_start=82
  _globals['_SERVERREQUEST']._serialized_end=119
  _globals['_SERVERRESPONSE']._serialized_start=121
  _globals['_SERVERRESPONSE']._serialized_end=169
  _globals['_REGISTERREQUEST']._serialized_start=171
  _globals['_REGISTERREQUEST']._serialized_end=227
  _globals['_REGISTERRESPONSE']._serialized_start=229
  _globals['_REGISTERRESPONSE']._serialized_end=264
  _globals['_CHATSERVICE']._serialized_start=266
  _globals['_CHATSERVICE']._serialized_end=335
  _globals['_NAMESERVICE']._serialized_start=338
  _globals['_NAMESERVICE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
